name: Process Updated Directories

on:
  push:
    branches:
      - main

jobs:
  list-directories:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Updated Directories
        id: list-directories
        run: echo "dirs=$(git diff --name-only --diff-filter=d HEAD~1..HEAD | sed -E 's|/[^/]+$||' | sort | uniq | paste -sd ',')" >> $GITHUB_ENV

  process-directory:
    runs-on: ubuntu-latest
    needs: list-directories
    strategy:
      matrix:
        directory: ${{ fromJson(needs.list-directories.outputs['list-directories.dirs']) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Process directory ${{ matrix.directory }}
        run: |
          # Process files in the updated directory
          echo "Processing directory ${{ matrix.directory }}"

      - name: Notify completion of processing directory
        run: echo "Completed processing directory ${{ matrix.directory }}"
