name: 1 Get Updated Directories

on:
  push:
    branches:
      - main

jobs:
  list-directories:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Updated Directories
        run: |
          # Get the difference between the current commit and the previous commit
          diff=$(git diff-tree -r --name-only HEAD HEAD~1)

          # Extract the directories from the difference
          updated_directories=$(echo $diff | sed -E 's|/[^/]+$||' | sort | uniq)

          # If there are any updated directories, print them out
          if [ -n "$updated_directories" ]; then
            for directory in $updated_directories; do
              echo "Directory $directory has been updated"
            done
          fi
