name: List Directories and Process Files
on:
  push:
    branches:
      - mains
jobs:
  list-directories:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.set-dirs.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set directories output
        id: set-dirs
        run: |
          echo "::set-output name=dirs::$(git diff-tree --no-commit-id --name-only -r HEAD | xargs dirname | sort | uniq)"
  process-files:
    runs-on: ubuntu-latest
    needs: list-directories
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.list-directories.outputs.dirs) }}
      max-parallel: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Process files in directory
        run: |
          echo "Processing files in directory ${{ matrix.dir }}..."
          # Add your commands or scripts here to process the files in the directory
