name: Build and Deployment
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print changed directories
        run: |
          for file in ${{ steps.changed-files.outputs.added_modified }}; do
            dir_name=$(dirname $file)
            echo $dir_name | cut -d '/' -f 1
          done | sort -u
      - name: Create dynamic build jobs
        run: |
          # Get the directory names
          dir_names=$(for file in ${{ steps.changed-files.outputs.added_modified }}; do
            dir_name=$(dirname $file)
            echo $dir_name | cut -d '/' -f 1
          done | sort -u)

          # Create a dynamic build job for each directory
          for dir_name in $comma_separated_dir_names; do
            name="build-$dir_name"
            jobs+="jobs:$name"
            steps+="
              - name: Build $dir_name
                run: |
                  echo 'Building $dir_name...'
                  yarn build $dir_name
            "
          done
          echo $jobs


