name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"
          echo "Directories:"
          echo "${{ steps.abc.outputs.added_modified }}" | sed -E 's|/[^/]+/?$||' | sort | uniq
