name: Build and Deployment

on:
  push:
    branches:
      - main

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      locales: ${{ steps.set_locales.outputs.locales }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Changed Files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Changed Directories
        id: set_locales
        run: |
          # Get the directory names
          dir_names=$(for file in ${{ steps.changed-files.outputs.added_modified }}; do
            dir_name=$(dirname $file)
            echo $dir_name | cut -d '/' -f 1
          done | sort -u)
          echo "locales=${dir_names}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locale: ${{ steps.set_locales.outputs.locales }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo "Building for locale ${{ matrix.locale }}"
      - name: Deploy
        run: |
          echo "Deploying for locale ${{ matrix.locale }}"
