name: Build and Deployment
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print changed directories
        id: print-dirs
        run: |
          dirs=()
          for file in ${{ steps.changed-files.outputs.added_modified }}; do
            dir_name=$(dirname $file) 
            dirs+=("$dir_name")
          done
          echo "::set-output name=dirs::${dirs[*]}"
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(steps.print-dirs.outputs.dirs) }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        run: |
          echo "Building and deploying directory ${{ matrix.directory }}..."
