name: Build and Deployment

on:
  push:
    branches:
      - main

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      locales: ${{ steps.set_locales.outputs.locales }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          json: true

      - name: Print Changed Directories
        id: set_locales
        run: |
          # Get the directory names
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          dir_names=${{ steps.changed-files.outputs.all_changed_files }}
          echo "locales=${dir_names}" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    name: Check ${{ matrix.nickname }}
    needs: [pre-build]
    strategy:
      matrix:
        locale: ${{fromJSON(needs.pre-build.outputs.locales)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo "Building for locale ${{ matrix.locale }}"
      - name: Deploy
        run: |
          echo "Deploying for locale ${{ matrix.locale }}"
