name: Build and Deployment
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print changed directories
        id: print-dirs
        run: |
          # Get the directory names
          dir_names=$(for file in ${{ steps.changed-files.outputs.added_modified }}; do
            dir_name=$(dirname $file)
            echo $dir_name | cut -d '/' -f 1
          done | sort -u)

          # Store the directory names in a variable
          comma_separated_dir_names=$dir_names
          echo $comma_separated_dir_names

  
